# Site settings
title: Fundación Ciudadano Inteligente
email: prensa@ciudadanointeligente.org
description: "Sitio web de la Fundación Ciudadano Inteligente"
baseurl: "//ciudadanointeligente.github.io/ciudadanoi"

# Build settings
markdown: kramdown
permalink: pretty

# Analytic
analytics :
 provider : google
 google :
     tracking_id : 'UA-31247996-1'
